//{{NO_DEPENDENCIES}}
// Microsoft Visual C++에서 생성한 포함 파일입니다.
// GIE_BoadAssy.rc에서 사용되고 있습니다.
//
#define IDC_BTN_FILE_SELECT             3
#define IDC_BTN_FW_VERSION              4
#define IDC_BTN_DOWNLOAD                5
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_GIE_BOADASSY_DIALOG         102
#define IDP_SOCKETS_INIT_FAILED         103
#define IDR_MAINFRAME                   128
#define IDD_TEST_READY                  129
#define IDC_LIST_PATTERNSET             130
#define IDD_MODEL_INFO                  130
#define IDD_INITIALIZE                  132
#define IDD_STATION                     133
#define IDD_MODEL_CHANGE                135
#define IDD_PATTERN_TEST                136
#define IDD_PANELID                     137
#define IDD_USERID                      138
#define IDD_DIALOG1                     139
#define IDD_GIE_JUDGE                   139
#define IDD_MESSAGE_ERROR               141
#define IDD_DIALOG2                     143
#define IDD_AUTO_FIRMWARE               143
#define IDI_ICON_ADD                    155
#define IDI_ICON_DELETE                 156
#define IDI_ICON_DOWN                   157
#define IDI_ICON_UP                     158
#define IDI_ICON_CHANGE                 160
#define IDC_BTN_USERID                  1000
#define IDC_BTN_MODELINFO               1001
#define IDC_BTN_FUSING                  1001
#define IDC_BTN_SYSTEM                  1002
#define IDC_BTN_CANCEL                  1002
#define IDC_BTN_EXIT                    1003
#define IDC_BTN_SAVE                    1003
#define IDC_BTN_TEST                    1004
#define IDC_EDT_H_TOTAL                 1004
#define IDC_BTN_SYSTEM2                 1005
#define IDC_BTN_INITIALIZE              1005
#define IDC_EDT_FREQ                    1005
#define IDC_EDT_H_ACTIVE                1006
#define IDC_BTN_MODEL_CHANGE            1006
#define IDC_EDT_H_WIDTH                 1007
#define IDC_BTN_AUTOFIRMWARE            1007
#define IDC_EDT_H_FRONT_PORCH           1008
#define IDC_BTN_BMP_DOWNLOAD            1008
#define IDC_EDT_H_BACK_PORCH            1009
#define IDC_EDT_V_TOTAL                 1010
#define IDC_EDT_V_ACTIVE                1011
#define IDC_EDT_V_WIDTH                 1012
#define IDC_EDT_V_FRONT_PORCH           1013
#define IDC_EDT_V_BACK_PORCH            1014
#define IDC_CMB_SIGNAL_TYPE             1015
#define IDC_CMB_SIGNAL_BIT              1016
#define IDC_CMB_LVDS_SEL                1017
#define IDC_CMB_BIT_SEL                 1018
#define IDC_CMB_GFD100                  1019
#define IDC_CMB_BIST_SEL                1020
#define IDC_CMB_CUR_PREEMP              1021
#define IDC_CMB_SOLOMON_MIPI            1022
#define IDC_CMB_EDP_INITCODE            1023
#define IDC_CMB_INTERFACE               1024
#define IDC_CMB_DCLK_INVERSE            1025
#define IDC_CMB_BIT_SWAP                1026
#define IDC_CMB_VSYNC_POLALITY          1027
#define IDC_CMB_HSYNC_POLALITY          1028
#define IDC_CMB_CLK_SET                 1029
#define IDC_EDT_CLK_DELAY               1030
#define IDC_EDT_VCC_SET                 1031
#define IDC_EDT_VDD_SET                 1032
#define IDC_EDT_VCC_HIGH_LIMIT          1033
#define IDC_EDT_VDD_HIGH_LIMIT          1034
#define IDC_EDT_ICC_HIGH_LIMIT          1035
#define IDC_EDT_IDD_HIGH_LIMIT          1036
#define IDC_EDT_ICC_CHECK               1037
#define IDC_CMB_PWR_SEQ_SEL             1038
#define IDC_EDT_PWR_SEQ_DELAY           1039
#define IDC_STT_CUR_MODEL               1040
#define IDC_EDT_CREATE_MODEL            1041
#define IDC_STT_CUR_MODELNAME_TIT       1042
#define IDC_STT_CREATE_MODEL_TIT        1043
#define IDC_CMB_EDID_ONOFF              1044
#define IDC_CMB_EDID_SIZE               1045
#define IDC_CMB_EDID_LINE               1046
#define IDC_CMB_EEPROM_TYPE             1047
#define IDC_CMB_VCOM_LINE               1048
#define IDC_CMB_VCOM_ADDR               1049
#define IDC_CMB_VCOM_BIT_SHIFT          1050
#define IDC_EDT_VCOM_MIN                1051
#define IDC_EDT_VCOM_MAX                1052
#define IDC_EDT_VCOM_DEFAULT            1053
#define IDC_EDT_VCOM_DROP               1054
#define IDC_EDT_BLU_MIN                 1055
#define IDC_BTN_BLU_ONOFF               1056
#define IDC_STT_PG_TIT                  1057
#define IDC_CMB_PTN_NAME                1057
#define IDC_CMB_SPI_MODE                1058
#define IDC_STT_PG_VALUE                1058
#define IDC_CMB_SPI_LEVEL               1059
#define IDC_EDT_EQP_NAME                1059
#define IDC_STT_BCR_TIT                 1059
#define IDC_EDT_MICRO_PTN_CNT           1060
#define IDC_CBO_PG_COMPORT              1060
#define IDC_STT_BCR_VALUE               1060
#define IDC_CBO_AUTO_BCR_COMPORT        1061
#define IDC_STT_GFD100_TIT              1061
#define IDC_EDT_PTN_FG                  1061
#define IDC_STT_GFD250_TIT              1061
#define IDC_CBO_GFD100_COMPORT          1062
#define IDC_STT_GFD100_VALUE            1062
#define IDC_EDT_PTN_BG                  1062
#define IDC_CBO_GFD250_COMPORT          1062
#define IDC_STT_GFD250_VALUE            1062
#define IDC_CBO_BLU_COMPORT             1063
#define IDC_STT_BLU_TIT                 1063
#define IDC_EDT_PTN_VCC                 1063
#define IDC_STT_BLU_VALUE               1064
#define IDC_EDT_PTN_VDD                 1064
#define IDC_EDT_TEST_START_DELAY        1064
#define IDC_EDT_PTN_TMS                 1065
#define IDC_STT_SYSTEM_TIT              1065
#define IDC_EDT_BLU_FREQ                1065
#define IDC_EDT_PTN_VSYNC               1066
#define IDC_STT_MODEL_TIT               1066
#define IDC_EDIT_MES_SERVICEPORT        1066
#define IDC_CMB_PTN_NAME2               1067
#define IDC_CMB_PTN_VCOM                1067
#define IDC_STT_SYSTEM_VALUE            1067
#define IDC_EDIT_MES_NETWORK            1067
#define IDC_STT_FG_CLK                  1068
#define IDC_STT_MODEL_VALUE             1068
#define IDC_EDIT_MES_DEMONPORT          1068
#define IDC_STT_BG_CLK                  1069
#define IDC_STT_EDID_TIT                1069
#define IDC_EDIT_MES_LOCALSUBJECT       1069
#define IDC_STT_VCC_CLK                 1070
#define IDC_STT_EDID_VALUE              1070
#define IDC_EDIT_MES_REMOTESUBJECT      1070
#define IDC_STT_VDD_CLK                 1071
#define IDC_STT_PATTERNFILE_TIT         1071
#define IDC_STT_TMS_CLK                 1072
#define IDC_STT_PTNFILE_VALUE           1072
#define IDC_STT_VSYNC_CLK               1073
#define IDC_STT_VCOM_CLK                1074
#define IDC_EDIT_MODELLIST              1075
#define IDC_EDT_PTN_BLU                 1075
#define IDC_BTN_LOAD                    1076
#define IDC_STT_BLU_CLK                 1076
#define IDC_CMB_EEPROM_ADDR             1077
#define IDC_BTN_ADD                     1078
#define IDC_BTN_DELETE                  1079
#define IDC_STT_VCC_SET                 1079
#define IDC_BTN_UP                      1080
#define IDC_STT_VCC_MEASURE             1080
#define IDC_BTN_DOWN                    1081
#define IDC_STT_VDD_MEASURE             1081
#define IDC_BTN_CHANGE                  1082
#define IDC_STT_VDD_SET                 1082
#define IDC_BTN_ALL                     1083
#define IDC_STT_TACT_TIME               1083
#define IDC_BTN_TEST_START              1083
#define IDC_STT_MODEL_NAME              1084
#define IDC_STT_IDD_MEASURE             1084
#define IDC_CMB_GFD250_ONOFF            1084
#define IDC_STT_TOTAL_CNT_TIT           1085
#define IDC_COMBO1                      1085
#define IDC_CMB_TEST_MODE               1085
#define IDC_STT_ICC_MEASURE             1085
#define IDC_CMB_PTN_TOUCH               1085
#define IDC_STT_GOOD_CNT_TIT            1086
#define IDC_STT_TOUCH_CLK               1086
#define IDC_CMB_TEST_MODE2              1086
#define IDC_CMB_BLU_TYPE                1086
#define IDC_STT_BAD_CNT_TIT             1087
#define IDC_CMB_FAST_JUDGE              1087
#define IDC_BTN_MICRO_PTN_PATH          1087
#define IDC_STT_TOTAL_CNT_VALUE         1088
#define IDC_CMB_PID_NG                  1088
#define IDC_STT_GOOD_CNT_VALUE          1089
#define IDC_STT_BAD_CNT_VALUE           1090
#define IDC_STT_STATUS_MSG              1091
#define IDC_LIST__PTN_VIEW              1092
#define IDC_STT_PANEL_ID_TIT            1092
#define IDC_STT_NUM                     1093
#define IDC_STT_PANEL_ID_VALUE          1093
#define IDC_STT_PTN_NAME                1094
#define IDC_EDT_PID                     1094
#define IDC_STT_VCC                     1095
#define IDC_BTN_RETRY                   1095
#define IDC_STT_VDD                     1096
#define IDC_BTN_QUALITY_SETUP           1096
#define IDC_STT_TMS                     1097
#define IDC_BTN_QUALITY_SETUP2          1097
#define IDC_BTN_QUALITY_FTP_SETUP       1097
#define IDC_EDIT_INPUT_ID               1097
#define IDC_STT_VSYNC                   1098
#define IDC_BTN_QUALITY_SETUP3          1098
#define IDC_BTN_MOD_FILE_PATH           1098
#define IDC_STT_FG                      1099
#define IDC_BTN_OK                      1099
#define IDC_BTN_PTN_FILE_PATH           1099
#define IDC_STT_BG                      1100
#define IDC_BTN_NG                      1100
#define IDC_BTN_EDID_FILE_PATH          1100
#define IDC_STT_VCOM                    1101
#define IDC_STT_ERR_MESSAGE             1101
#define IDD_MESSAGE_QUESTION            1102
#define IDC_STT_PTN_LIST_TITLE          1102
#define IDC_BTN_MSG_CONFIRM             1103
#define IDC_STT_PTN_TEST_MESSAGE        1103
#define IDC_BTN_MSG_CLOSE               1104
#define IDC_BTN_ERR_CLOSE               1105
#define IDC_STT_MSG_MESSAGE             1106
#define IDC_STT_MICRO_PTN_PATH          1107
#define IDC_STT_EQP_NAME_VALUE          1108
#define IDC_STT_OP_MODE_VALUE           1109
#define IDC_STT_USER_ID_VALUE           1110
#define IDC_STT_USER_NAME_VALUE         1111
#define IDC_STT_MODEL_NAME_VALUE        1112
#define IDC_STT_RESOLUTION_VALUE        1113
#define IDC_STT_SIGNALBIT_VALUE         1114
#define IDC_STT_VCC_VALUE               1115
#define IDC_STT_VDD_VALUE               1116
#define IDC_STT_IDD_VALUE               1117
#define IDC_STT_ICC_VALUE               1118
#define IDC_STT_STATION_INFO_TIT        1119
#define IDC_STT_MODEL_INFO_TIT          1120
#define IDC_STT_EQP_NAME_TIT            1121
#define IDC_STT_OP_MODE_TIT             1122
#define IDC_STT_USER_ID_TIT             1123
#define IDC_STT_USER_NAME_TIT           1124
#define IDC_STT_MODEL_NAME_TIT          1125
#define IDC_STT_RESOLUTION_TIT          1126
#define IDC_STT_SIGNALBIT_TIT           1127
#define IDC_STT_VOLT_TIT                1128
#define IDC_STT_CURR_TIT                1129
#define IDC_STT_VCC_TIT                 1130
#define IDC_STT_VDD_TIT                 1131
#define IDC_STT_GRP_SIGNAL              1132
#define IDC_STT_GRP_TIMING              1133
#define IDC_STT_GRP_POWER               1134
#define IDC_STT_GRP_OTHERS              1135
#define IDC_STT_GRP_CLOCK               1136
#define IDC_STT_GRP_EDID                1137
#define IDC_STT_GRP_VCOM                1138
#define IDC_STT_GRP_PATTERN             1139
#define IDC_STT_USERID_TIT              1140
#define IDC_STT_GRP_OTHERS2             1140
#define IDC_STT_USERDLG_TIT             1141
#define IDC_STT_MCDLG_TIT               1142
#define IDC_STT_MODELINFODLG_TIT        1143
#define IDC_STT_INITDLG_TIT             1144
#define IDC_STT_STATIONDLG_TIT          1145
#define IDC_STT_AUTOFWDLG_TIT           1146
#define IDC_STT_FILE_PATH               1147
#define IDC_STT_FW_VERSION              1148
#define IDC_PROGRESS_DOWNLOAD           1149
#define IDC_STT_FW_STATUS               1150
#define IDC_STT_GFD250_STATUS           1150
#define IDC_STT_SYSTEM_STATUS           1151
#define IDC_STT_SYSTEM_STATUS_TIT       1152
#define IDC_STT_GFD250_STATUS_TIT       1153
#define IDC_CMB_TARGET_SELECT           1154
#define IDC_STT_TARGET_SEL              1155
#define IDC_STT_SYS_TIT                 1156
#define IDC_STT_PORT_TIT                1157
#define IDC_STT_MES_TIT                 1158
#define IDC_IPADDRESS_LOCAL_IP          1159
#define IDC_STT_PATH_TIT                1160
#define IDC_EDT_MOD_FILE_PATH           1161
#define IDC_EDT_PTN_FILE_PATH           1162
#define IDC_BTN_APL                     1162
#define IDC_BTN_APPLY                   1162
#define IDC_EDT_EDID_FILE_PATH          1163
#define IDC_STT_VCC_SET_TIT             1163
#define IDC_STT_VCC_MEA_TIT             1164
#define IDC_STT_ICC_MEA_TIT             1165
#define IDC_STT_IDD_MEA_TIT             1166
#define IDC_STT_VDD_MEA_TIT             1167
#define IDC_STT_VDD_SET_TIT             1168
#define IDC_STT_TT_TIT                  1169
#define IDC_PIC_MD_PTN_PREVIEW          1170
#define IDC_STT_EQP_NAME                1171
#define IDC_STT_TEST_MODE               1172
#define IDC_STT_BLU_TYPE                1173
#define IDC_STT_BLU_FREQ                1174
#define IDC_STT_TEST_START_DELAY        1175
#define IDC_STT_FAST_JUDGE              1176
#define IDC_STT_PANELID_NG              1177
#define IDC_STT_PG_PORT                 1178
#define IDC_STT_GFD250_PORT             1179
#define IDC_STT_AUTO_BCR_PORT           1180
#define IDC_STT_BLU_PORT                1181
#define IDC_STT_MES_SERV_PORT           1182
#define IDC_STT_MES_NETWORK             1183
#define IDC_STT_MES_DEAMON              1184
#define IDC_STT_MES_LOCAL_SUBJ          1185
#define IDC_STT_MES_REMOTE_SUBJ         1186
#define IDC_STT_MES_LOCAL_IP            1187
#define IDC_STT_MODEL_PATH              1188
#define IDC_STT_PATTERN_PATH            1189
#define IDC_STT_EDID_FILE_PATH          1190
#define IDC_LIST_PATTERN_TEST_MASSAGE   1191
#define IDC_STT_TP_COLOR_R_VAL          1193
#define IDC_STT_TP_COLOR_G_VAL          1194
#define IDC_STT_TP_COLOR_B_VAL          1195
#define IDC_STT_MAIN_FW_VERSION_VIEW    1195
#define IDC_STT_TP_EDID_RESULT          1196

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        162
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1196
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
